In [2]:
import random
import numpy as np

# Define the directions
UP, DOWN, LEFT, RIGHT = 0, 1, 2, 3

def merge_left(row):
    """ Helper function to merge a single row to the left as per 2048 rules """
    non_zero = row[row != 0]
    merged = []
    skip = False
    for i in range(len(non_zero)):
        if skip:
            skip = False
            continue
        if i+1 < len(non_zero) and non_zero[i] == non_zero[i+1]:
            merged.append(2*non_zero[i])
            skip = True
        else:
            merged.append(non_zero[i])
    merged.extend([0]*(len(row) - len(merged)))
    return np.array(merged)

def move_left(grid):
    """ Move the grid left as per 2048 rules """
    return np.array([merge_left(row) for row in grid])

def move_right(grid):
    """ Move the grid right as per 2048 rules """
    return np.fliplr(move_left(np.fliplr(grid)))

def move_up(grid):
    """ Move the grid up as per 2048 rules """
    return np.rot90(move_left(np.rot90(grid, -1)), 1)

def move_down(grid):
    """ Move the grid down as per 2048 rules """
    return np.rot90(move_left(np.rot90(grid, 1)), -1)

def get_empty_cells(grid):
    """ Get a list of empty cells """
    return [(i, j) for i in range(4) for j in range(4) if grid[i][j] == 0]

def add_new_tile(grid):
    """ Add a new tile (2 or 4) in a random empty cell """
    empty_cells = get_empty_cells(grid)
    if not empty_cells:
        return grid
    i, j = random.choice(empty_cells)
    grid[i][j] = 2 if random.random() < 0.9 else 4
    return grid

def calculate_heuristic(grid):
    """ A simple heuristic: prioritize emptier boards and higher tile values """
    return np.sum(grid == 0) + np.max(grid)

def simulate_move(grid, direction):
    """ Simulate the move in the specified direction """
    if direction == UP:
        return move_up(grid)
    elif direction == DOWN:
        return move_down(grid)
    elif direction == LEFT:
        return move_left(grid)
    elif direction == RIGHT:
        return move_right(grid)

def ai_move(grid):
    """ AI chooses the best move based on heuristic evaluation """
    best_move = None
    best_score = -float('inf')
    for direction in [UP, DOWN, LEFT, RIGHT]:
        new_grid = simulate_move(grid, direction)
        if not np.array_equal(new_grid, grid):  # Only consider valid moves
            score = calculate_heuristic(new_grid)
            if score > best_score:
                best_score = score
                best_move = direction
    return best_move

def play_game():
    """ Main function to play the game """
    grid = np.zeros((4, 4), dtype=int)
    grid = add_new_tile(grid)
    grid = add_new_tile(grid)

    while True:
        print("State before move:")
        print(grid)

        direction = ai_move(grid)
        if direction is None:
            print("No more moves possible. Game over!")
            break

        print(f"AI chooses to move: {['up', 'down', 'left', 'right'][direction]}")

        grid = simulate_move(grid, direction)
        grid = add_new_tile(grid)

        print("State after adding new tile:")
        print(grid)
        print()

if __name__ == "__main__":
    play_game()


State before move:
[[0 0 0 0]
 [0 0 0 2]
 [0 0 0 4]
 [0 0 0 0]]
AI chooses to move: up
State after adding new tile:
[[0 0 0 0]
 [0 2 0 0]
 [0 0 0 2]
 [0 0 0 4]]

State before move:
[[0 0 0 0]
 [0 2 0 0]
 [0 0 0 2]
 [0 0 0 4]]
AI chooses to move: up
State after adding new tile:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 2 2]
 [0 2 0 4]]

State before move:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 2 2]
 [0 2 0 4]]
AI chooses to move: left
State after adding new tile:
[[0 0 0 0]
 [0 0 0 0]
 [4 2 0 0]
 [2 4 0 0]]

State before move:
[[0 0 0 0]
 [0 0 0 0]
 [4 2 0 0]
 [2 4 0 0]]
AI chooses to move: down
State after adding new tile:
[[4 2 0 0]
 [2 4 0 0]
 [0 2 0 0]
 [0 0 0 0]]

State before move:
[[4 2 0 0]
 [2 4 0 0]
 [0 2 0 0]
 [0 0 0 0]]
AI chooses to move: up
State after adding new tile:
[[0 0 2 0]
 [0 2 0 0]
 [4 4 0 0]
 [2 2 0 0]]

State before move:
[[0 0 2 0]
 [0 2 0 0]
 [4 4 0 0]
 [2 2 0 0]]
AI chooses to move: left
State after adding new tile:
[[2 0 0 0]
 [2 0 0 0]
 [8 0 0 0]
 [4 4 0 0]]

State before move:
[[2